# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.23.2
_src_path: gh:seedcase-project/template-website
author_family_name: Brødbæk
author_given_name: Signe Kirk
github_repo: digital-aarskontrol
github_user: steno-aarhus
hosting_provider: gh-pages
is_seedcase_website: false
template_type: simple
website_format: website
