project:
  type: sdca-theme

website:
  title: "Digital årskontrol"
  site-url: "https://steno-aarhus.github.io/digital-aarskontrol/"
  repo-url: "https://github.com/steno-aarhus/digital-aarskontrol"
  # TODO: Set favicon if relevant.

  navbar:
    left: 
    - text: "For almen praksis"
  menu:
    - text: "Mere om projektet"
      href: mere-om-projektet.qmd
    - text: "Bilag"
          href: bilag.qmd

      - text: "For patienter"
        href: for-patienter.qmd    
      - text: "Kontakt og tilmelding"
        href: kontakt.qmd
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/digital-aarskontrol"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Denne hjemmeside er under udvikling. Nogle sider kan mangle indhold eller være midlertidigt utilgængelige."
format:
  sdca-theme-html:
    theme:
      - brand
      - custom-styles.scss

editor: 
  markdown:
    wrap: 72
    canonical: true
