#For almen praksis
---

### Om projektet
Projektet vil undersøge, om hver anden årskontrol hos voksne med velbehandlettype 2-diabetes kan erstattes af en digital model uden at behandlingskvaliteten påvirkes negativt.  
Forsøget vil løbe over to år og blive evalueret på, om deltagerne i det digitale forløb klarer sig lige så godt vedrørende HbA1c, som personer med type 2-diabetes, der følger en standard årskontrol. Desuden vil projektet følge forbruget af konsultationer, øvrige diabetesrelevante værdier, herunder blodtryk, kolesterol, eGFR, UACR og medicin.


# Almen praksis' opgaver i forbindelse med projektet.
1.	Identifikation potentielle deltagere via patientlisten i forløbsoverblikket og ved opslag i journalen eller generelt kendskab til patinten.  
2.	Rekruttering af deltagere. 
3. Afholdelse af digital årskontrol
4. Indsendelse af oplysninger om deltagere (årstal for diabetesdiagnose, blodtryk, vægt og rygestatus ved projekt start og slut). 


### Honorar 
Klinikken honoreres for projektaktiviteter; honoraret er specificeret i samarbejdsaftalen, der fremsendes ved tilmelding.
Honorar pr. deltager svarer til én times arbejdstid

## 📋 Tilmelding
Projektet henvender sig til almen praksis i Region Midtjylland og forventes at starte i september 2026 og have en varighed på 24 måneder.
Når I tilmelder jeres klinik, registreres I som interesserede. Pladserne fordeles efter først-til-mølle-princippet. 
Senest fem hverdage efter tilmelding vil I modtage yderligere information om projektet samt en samarbejds- og databehandleraftale, som skal underskrives, inden den endelige tilmelding er gyldig.

Ved at udfylde formularen accepterer I, at vi behandler jeres oplysninger i projektet. Oplysningerne bruges udelukkende til at registrere tilmeldinger og kontakte jer efterfølgende.  
Tilmeldingen er først registreret, når I har trykket på "Tilmeld" og modtager beskeden: "Tak for din tilmelding".
<details> <summary><strong>Er tilmelding bindende?</strong></summary> 
Nej. Tilmelding er i første omgang uforpligtende. Den endelige deltagelse aftales ved indgåelse af samarbejdsaftale. </details> 
Udfyld tilmeldingsformularen herunder for at tilmelde jeres lægepraksis:


# Identifikation og rekruttering af deltagere 
Identifikation af potentielle deltagere:  
1. Almen praksis anvender Patientlisten i Forløbsoverblikket til identifikation af patienter som opfylder de "hårde" paraklinikse inklusionskriterier (HbA1c, eGFR, UACR, LDL). Se: link til "hvem kan deltage. 
2. Ved opslag i journalen eller udfra det generelle kendskab til vurderes om patienten er egnet til digital årskontrol. Vurdering af comorbiditet, samt digitale og sproglige evner. Er der forhold som gør patienten uegnet?
Der er ikke fastsat bestemt tilstande eller komorbiditeter, som gør pateinten uegnet. Det er en invididuel afgørelse af behandleren. 
Rekrutteringsprocessen er udførligt beskrevet i bilag 2, Procedure for mundtlig deltagerinformation.
	
Rekruttering af deltagere foregår i 3 trin:
Trin 1. Besked i Min Læge-appen med forespørgsel om deltagelse (bilag 3).
Trin 2. Mundtligt deltagerinformation givet telefonisk eller ved fremmøde, hvis patienten af anden årsag er i klinikken, hvor der er tid og mulighed til afgivelse af mundtlig information (bilag 2).
Trin 3. Besked i Min Læge-appen med link til samtykke (bilag 4).

# Samtykke
Samtykke registreres direkte hos Steno Diabetes Center Aarhus og opbevares dér. 
Oplysning om deltagers samtykke videregives til almen praksis via e-Boks. 

# Praktisk gennemførelse
Efter rektruttering og indhentet samtykke vil deltagerens kommende årskontrol for type 2-diabetes blive gennemført digitalt. Deltageren møder som vanligt til blod- og urinprøve, men måler selv blodtryk (og eventuelt vægt), indsender oplysninger om rygning, motion og alkohol og besvarer et spørgeskema, der screener for senkomplikationer, og som også giver patienten mulighed for at ønske en samtale om sin diabetes. Når alle oplysninger er modtaget, vurderer deltagerens vanlige behandler prøvesvarene og spørgeskemaet, og sender svar på resultaterne til deltageren via Min Læge-app.
Hvis der findes forhold, som kræver behandlingstiltag, er det op til den ansvarlige behandler at vurdere, om dette kan gøres over mail eller telefon eller kræver, at deltageren bestiller en tid. 
Deltagerens diabetes årskontrol det efterfølgende år, er igen en standard årskontrol med fysisk fremmøde. 
Der tages i forsøget ingen ekstra blodprøver eller udføres yderligere undersøgelser ud over dem, deltageren normalt får i forbindelse med en diabetes årskontrol. Det eneste, der ændres, er måden, deltageren og behandleren kommunikerer ved årskontrollen. 
I hele perioden skal deltageren i øvrigt kontakte sin læge, fuldstændigt som de plejer.

# Størrelse og lokation
Alle praksis i Region Midt inviteres til at deltage. Målet er deltagelse fra cirka 25 almen praksis klinikker og cirka patienter medtype 2-diabetes. 
Hvis interessen for deltagelse bliver væsentligt større end studiets kapacitet vil projektet se sig nødsaget til at lukke for tilmeldinger.
Til det kvalitative interviewstudie vil cirka 15 deltagere inviteres til at deltage. 

# Evaluering
Projektet vil blive evalueret på, om deltagerne i det digitale forløb klarer sig lige så godt vedrørende HbA1c, som personer med type2-diabetes, der følger en standard årskontrol. 
Desuden vil projektet følge øvrige diabetesrelevante værdier, herunder blodtryk, kolesterol, eGFR og UACR, diabetes relevavant medicin og forbruget af sundhedsydelser.   


# Økonomiske forhold
Forsøget er finansieret af Steno Diabetes Center Aarhus.
Deltagerne modtager ikke betaling for deltagelse i forsøget. 
Deltagende almen praksis modtager betaling for tidsforbrug til rekruttering og dataindsamling.  

Du kan læse studiets protokolresumé under fanen bilag.


## ❓FAQ 
### Typiske spørgsmål




Efter en kort elektronisk oplæring kan klinikken begynde at spørge patienter og registrere svar. Ved spørgsmål eller tvivl kan klinikken kontakte projektkoordinator Kirsten Christensen.

📧 kichis\@rm.dk  

☎️  </details> 

📌 <details> <summary><strong>Hvilke patienter kan indgå?</strong></summary> 

Projektet omfatter patienter med type 2-diabetes, som opfylder inklusionskriterierne:
•	Myndige voksne over 18 år med type 2 diabetes, som følges i almen praksis.
•	eGFR > 59 ml/min/1,73 m².
•	HbA1c: < 48 mmol/mol, eller 48–53 mmol/mol hvis det individuelle mål for langtidsblodsukkeret er < 53 mmol/mol.
•	Urin albumin/kreatinin-ratio (UACR):< 30 mg/g eller 30–300 mg/g, hvis deltageren er i behandling med organbeskyttende medicin.
•	LDL-kolesterol < 2,6 mmol/L.

•	Desuden skal kunne bruge den danske nationale sundhedsportal (www.sundhed.dk), samt  læse og forstå dansk.

Forhold som udelukker patienten fra at deltage: 
•	Hvis den behandlingsansvarlige vurderer personen uegnet til digital årskontrol grundet fx alvorlige komorbiditeter eller andre forhold. 
•	Graviditet. 



</details>

 <details> <summary><strong>Hvor meget tid skal vi bruge på projektet?</strong></summary> 
Relevante medarbejdere gennemfører en kort elektronisk oplæring med et forventet tidsforbrug på ca. 15 minutter. Samtalen kan gennemføres på under 2 minutter pr. patient og er tilrettelagt, så den kan integreres i eksisterende arbejdsgange. Indhentning af samtykke forventes at tage yderligere ca. 2 minutter. Alle medarbejdere i klinikken kan gennemføre interventionen og den kan fx implementeres ved prøvetagning forud for årsstatus. </details> 

<details> <summary><strong>Hvordan registreres patienterne?</strong></summary> 
Registrering af patienternes udsagn sker via en enkel onlineformular. </details>

<details> <summary><strong>Hvordan indhentes samtykke fra patienterne?</strong></summary> 
Som en del af samtalen informeres patienten om projektets formål, hvilke oplysninger der videregives, og hvordan oplysningerne anvendes til forskning.

Patienten gives mundtlig information og der udleveres en skriftlig information og en samtykkeerklæring, som gennemgås og underskrives.  
Samtykket omfatter: 

 - videregivelse af relevante oplysninger fra almen praksis til Afdeling for Folkeundersøgelser, og 

 - anvendelse af de videregivne oplysninger til forskningsformål i overensstemmelse med sundhedslovens § 10.

Deltagelse er frivillig, og patienten kan til enhver tid trække sit samtykke tilbage uden betydning for den øvrige behandling.

Klinikken noterer samtykke til videregiveelse af oplysninger i patientjournalen og opbevarer skriftlige samtykkeerklæringer, indtil projektet afsluttes og de indsamles af Steno Diabetes Center Aarhus. 

 </details>

 <details> <summary><strong>Hvordan håndteres data og patientoplysninger?</strong></summary>
Projektet gennemføres i overensstemmelse med gældende regler om databeskyttelse og sundhedslovgivning.  
Der indsamles kun de nødvendige oplysninger, og alle data behandles fortroligt og sikkert.
</details>

 <details> <summary><strong>Er der andre opgaver i almen praksis?</strong></summary>
Ved projektets afslutning indsender klinikken ti nøgletal:

- Antal patienter i målgruppen (Type 2-diabetes, 51-74 år)
- Antal patienter i målgruppen med gennemført årskontrol i projektperioden

Enkelte klinikker inviteres til at deltage i et kort opfølgende interview (ekstra honorar)
</details>

## 💻 E-læring
- **[Instruktionsvideo](https://vimeo.com/1191666872)**: Se videoen ved at trykke på linket. Videoen kan bruges alene eller som supplement til det skriftlige materiale. Se evt videoen med 1,5 x hastighed.
- **[Skriftligt oplæringsmateriale](/images/oplæringsmaterialetilpilot.pdf)**: Kan bruges alene eller som supplement til videoen. 

## 📂 Materialer
Herunder finder du relevante materialer til brug i projektet:

- **[Online formular til registrering af patienter og evt. bestilling af prøvesæt](https://selvbetjening.rm.dk/rm/Login/LoginMitId?returnUrl=/rm/Opret/8da94783df402)**: Tryk her for at komme til login-siden for projektets registreringsformular.
- **[Lommekort](/images/Lommekort_pilot.pdf)**: Trin-for-trin vejledning til procedurer i projektet.
- **[Patientinformation](/images/Patientinformation og samtykke.pdf)**: Information som udleveres til alle patienter, der registres i projektet. 
