
### Hvad går projektet ud på? 
Projektet går i korte træk ud på, at du hvert andet år ikke kommer til konsultation hos lægen eller sygeplejersken, når du skal have svar på dine diabetes årskontrolprøver, men i stedet får en mail fra lægen eller sygeplejersken med svar på prøverne. Du skal altså stadig have taget de sædavanlige prøver, og besvare et spørgeskema omkring livsstil og din diabetes. Det eneste der er ændret er, at måden du kommunikerer med din behandler på i forbindelse med årskontrollen.


### Ofte stillede spørgsmål

::: {.callout collapse="true"}
## **Hvad er formålet med projektet??**
Forsøgets formål er at udvikle og afprøve en ny model for, hvordan almen praksis kan udføre diabetes årskontrol hos personer med velbehandlet type 2-diabetes. Modellen kalder vi Digital Årskontrol.
Traditionelt foregår kontrollerne for personer med type 2-diabetes i Danmark ved, at personen med type 2-diabetes møder op til en årskontrol én gang om året. Da antallet af danskere med type 2 diabetes stiger, gælder dette for flere og flere, men heldigvis er der også flere end tidligere, som er velbehandlede.
For at sikre, at der i fremtiden fortsat er ressourcer til de mest syge personer med type 2-diabetes, er det nødvendigt at prioritere ressourcerne anderledes. Samtidig efterspørger mange patienter og politikere digitale tilbud fra sundhedsvæsenet.  Vi vil derfor med forsøget undersøge, om det er sikkert for personer med velbehandlede type 2-diabetes, at blive fulgt med en digital årskontrol hvert andet år. 
:::

::: {.callout collapse="true"}
## **Hvad betyder det for mig, hvis jeg siger ja til at deltage?**
Hvis du giver samtykke til at deltage i forsøget, vil din næste årskontrol vil blive digital.
Det foregår på den måde, at du får taget blod- og urinprøve på samme måde, som du er vant til. Du vil også modtage en besked via Min Læge-appen, hvor du vil blive bedt om selv at lave hjemmeblodtryksmålinger og veje dig, hvis du har en badevægt. 
Samtidig skal du besvare et spørgeskema vedrørende KRAM-faktorer (spørgsmål om kost, rygning, alkoholforbrug og motion), og et kort spørgeskema med 5-6 spørgsmål, som screener for symptomer på komplikationer, spøger til udfordringer med din medicin og spørger ind til, om du har behov for en samtale om din diabetes. Begge spørgeskemaer tilsendes via Min Læge-appen eller kan tilgås via link modtaget på SMS eller e-mail. 
Når alle svar foreligger, ser og evaluerer din faste diabetesbehandler prøvesvarene, og sender dig mailsvar i Min Læge-appen. 
Hvis din behandler finder forhold, som kræver handling, er det op til din behandler at vurdere, om denne information kan drøftes over mail eller telefon eller kræver, at du bestiller en tid. 
Hvis du i spørgeskemaet har ønsket samtale om din diabetes, vil I aftale en tid til dette. 
Året efter at du har haft den digitale årskontrol, vil din årskontrol igen være en årskontrol med fysisk fremmøde hos din behandler.
I hele projektperioden skal du i øvrigt kontakte din læge, når du vurderer, at du har behov for det, fuldstændig som du plejer. Det eneste, der er ændret er, at svaret på dine årskontrolprøver bliver givet på mail. 
:::

::: {.callout collapse="true"}
## **Hvor lang tid varer projektet?**
Forsøget varer cirka 2 år. Det starter, når du har givet samtykke.  Efter afgivelse af samtykke vil din kommende årskontrol være digital.  Året efter, at du har haft den digitale årskontrol, vil din årskontrol igen være en årskontrol med fysisk fremmøde hos din behandler. Forsøget slutter når vi har modtaget oplysninger fra din læge om, at I har afholdt årskontrollen med fysisk fremmøde, som ligger året efter din digitale årskontrol. 
:::

::: {.callout collapse="true"}
## **Hvem kan deltage?**
Der er plads til at ca. 600 patienter fra cirka 25 almen praksis i Region Midtjylland ka deltage.
For at du som patient kan deltage i projektet kræver det, at din praktiserende læge er tilmeldt projektet. Desuden kræver det, at du er velbehandlet vurderet udfra nogle fastsatte kriterier, samt at din læge vurderer, at du egner dig til digital årskontrol. Det kan fx. være, at du har andre sygdomme, som gør at din læge vurderer, at du ikke egner dig til digital årskontrol.  
:::

::: {.callout collapse="true"}
## **Hvornår starter projektet?**
Vi forventer at projektet opstarter per 1.9.2026. 
:::

::: {.callout collapse="true"}
## **Hvorfor deltage?**
Ved at deltage i forsøget bidrager du med viden om: 
- Hvordan almen praksis sikkert kan differentiere behandlingsforløb til personer med type 2-diabetes, så der frigøres ressourcer fra de mindst syge, til dem med størst behov
- Hvordan man i fremtiden kan planlægge behandlingsforløb af personer med type 2-diabetes, så de som ønsker en digital årskontrol, sikkert kan få dette. 
- Hvordan organiseringen af sikker og retfærdig diabetesbehandling kan tilrettelægges.
- Hvad der skal til, for at det føles sikkert for en person med type 2-diabetes at blive fulgt digitalt. 
- Hvordan den digitale årskontrol kan implementers, hvem den egner sig til, og om der er særlige individuelle behov, man bør tage højde for. 
:::

::: {.callout collapse="true"}
## **Er der risici og ulmemper ved at deltage**
Vi forventer ikke, at din deltagelse vil medføre nogle væsentlige ulemper eller risici for dig.  Du vil blive fulgt med sædvanlige årskontrolprøver og alene formidlingen af årskontrolsvaret ændres. I forsøgsperioden skal du i øvrigt kontakte din læge som sædvanligt.
Der er en lille risiko for, at en negativ udvikling i din diabetes ville kunne være blevet opdaget tidligere ved hyppigere målinger. Den risiko vurderes dog som acceptabel, da én årlig kontrol vurderes at være i overensstemmelse med gældende retningslinjer for personer med velbehandlet type 2-diabetes.  
Der kan være uforudsete risici og belastninger forbundet med forsøget.
Forsøget er godkendt af Videnskabsetisk komité (anmeldelsesnummer: 122999). 
Alle som deltager i forsøget er dækket af patienterstatningen.
:::

::: {.callout collapse="true"}
## **Hvordan opbevares og behandles mine data**
Alle dine personlige data opbevares og behandles fortroligt og i overensstemmelse med GDPR.  
Databeskyttelsesloven overholdes ved behandlingen af personoplysninger i projektet.
Steno Diabetes Center Aarhus indsamler data og opbevarer dem sikkert i en beskyttet database. Kun medarbejdere, der arbejder med forsøget, kan tilgå dine data." Forsøget registreres i den interne fortegnelse i Region Midtjylland.
Forsøget overfører ikke personoplysninger til udlandet.
Når forsøget er afsluttet, vil data blive slettet.
:::



