---
title-block-banner: true
title: "Digital årskontrol"
# subtitle: "Kan patienter med velreguleret type 2- diabetes følges digitalt uden at kvaliteten af behandlingen forringes?"
---

Denne hjemmeside er under udvikling.
---
title-block-banner: true
title: "Digital årskontrol"
subtitle: "Kan patienter med velreguleret type 2- diabetes følges digitalt uden at kvaliteten af behandlingen forringes?"
listing: 

# Velkommen til hjemmesiden om projekt digital årskontrol. 

# Hvad er projekt digital årskontrol?
Projektet vedrører patienter med velbehandlet type 2‑diabetes, som følges hos egen læge. Projektet vil undersøge, om hver anden årskontrol hos voksne med velbehandlettype 2-diabetes kan erstattes af en digital årskontrol uden at behandlingskvaliteten påvirkes negativt. Det foregår på den måde, at patienten hver andet år ikke møder til konsultation hos lægen eller sygeplejersken for at få svar på deres årskontrolprøver, men i stedet modtager svarene som en mail fra lægen eller sygeplejersken.  
Deltagerne i projektet skal stadig have foretaget årsprøver i form af blod- og urinprøve, samt lave hjemmeblodtyksmålinger og svare på spørgsmål om levevis og symtomer på eventuelle senkomplikationer. 
Det eneste, der er ændret, er, at svaret på deres årskontrolprøver bliver givet på mail. 

# Hvad er formålet med projeket?
Formålet er at udvikle og afprøve en ny model for, hvordan almen praksis kan udføre diabetes årskontrol hos personer med velbehandlet type 2-diabetes. 
Traditionelt foregår kontrollerne for personer med type 2-diabetes i Danmark ved, at personen med type 2-diabetes møder op til en årssamtale eller statussamtale én gang om året. 
Antallet af danskere med type 2‑diabetes stiger, så dette berører flere og flere personer — men heldigvis er der også godt nyt, da en større andel end tidligere, er velbehandlede. 
For at sikre, at der i fremtiden fortsat er ressourcer til dem, der har mest brug for det, er det nødvendigt at prioritere sundhedsvæsenets ressourcer. 
Samtidig efterspørger mange patienter og politikere digitale tilbud fra sundhedsvæsenet.  
Vi vil derfor med forsøget undersøge, om det er sikkert for personer med velbehandlede type 2-diabetes, at blive fulgt med en digital årskontrol hvert andet år.  

# Hvor lang tid varer projektet?
Projektet varer cirka 2 år. Det starter, når deltageren har givet samtykke.  Efter afgivelse af samtykke vil deltagerens kommende årskontrol være digital.  Året efter, at deltageren har haft den digitale årskontrol, vil den efterfølgende årskontrol igen være en årskontrol med fysisk fremmøde. Forsøget slutter når vi har modtaget oplysninger om, at årskontrollen med fysisk fremmøde, som ligger året efter den digitale årskontrol, er afholdt.

# Hvornår starter projektet?
Projektet forventes at starte d. 1. september 2026. 

# Hvordan evalueres projektet?
Projektet vil blive evalueret på, om deltagerne i det digitale forløb klarer sig lige så godt vedrørende HbA1c, som personer med type2-diabetes, der følger en standard årskontrol. 
Desuden vil projektet følge øvrige diabetesrelevante værdier, herunder blodtryk, kolesterol, eGFR og UACR, diabetes relevavant medicin og forbruget af sundhedsydelser.   

# Hvem kan deltage?
Alle praktiserende læger i Region Midt kan deltage. 
<details> <summary><strong>Hvilke patienter kan deltage?</strong></summary> 
Voksne med type 2-diabetes, som følges hos egen læge, OG som opfylder følgende kriterier:
-	Nyrefunktion, eGFR > 59 ml/min/1,73 m².
-	Langtidsblodsukker, HbA1c: < 48 mmol/mol, eller 48–53 mmol/mol hvis det individuelle mål for langtidsblodsukkeret er < 53 mmol/mol.
- Albumin/kreatinin ratio, UACR:< 30 mg/g eller 30–300 mg/g, hvis deltageren er i behandling med organbeskyttende medicin.
- LDL-kolesterol < 2,6 mmol/L.
- Desuden skal den behandligsansvarlige læge eller dennes uddelegrede vurdere, at patienten egner sig digital årskontrol. Fx. kan komorbiditeter eller manglende digitale eller sproglige evner betyde, at patienten ikke vurderes egnet. 
Gravide kan ikke deltage. 




::: {#listing}
:::


