#Mere om projektet

#Praktisk gennemførelse
Efter rektruttering og indhentet samtykke vil deltagerens kommende årskontrol for type 2-diabetes blive gennemført digitalt. Deltageren møder som vanligt til blod- og urinprøve, men måler selv blodtryk (og eventuelt vægt), indsender oplysninger om rygning, motion og alkohol og besvarer et spørgeskema, der screener for senkomplikationer, og som også giver patienten mulighed for at ønske en samtale om sin diabetes. Når alle oplysninger er modtaget, vurderer deltagerens vanlige behandler prøvesvarene og spørgeskemaet, og sender svar på resultaterne til deltageren via Min Læge-app.
Hvis der findes forhold, som kræver behandlingstiltag, er det op til den ansvarlige behandler at vurdere, om dette kan gøres over mail eller telefon eller kræver, at deltageren bestiller en tid. 
Deltagerens diabetes årskontrol det efterfølgende år, er igen en standard årskontrol med fysisk fremmøde. 
Der tages i forsøget ingen ekstra blodprøver eller udføres yderligere undersøgelser ud over dem, deltageren normalt får i forbindelse med en diabetes årskontrol. Det eneste, der ændres, er måden, deltageren og behandleren kommunikerer ved årskontrollen. 
I hele perioden skal deltageren i øvrigt kontakte sin læge, fuldstændigt som de plejer.

Projeket omfatter to metodiske komponenter:
1.	Et prospektivt kohortestudie med to års opfølgning, hvor deltagerne sammenlignes med en matchet kontrolgruppe. Deltagerne vil blive fulgt med hensyn til udvikling i langtidsblodsukker, nyrefunktion, kolesterol, sygelighed, medicinforbrug, antallet af målinger af langtidsblodsukker samt forbrug af sundhedsydelser i primær- og sekundærsektoren. 
2.	Et kvalitativt studie, der undersøger deltagende patienter og behandleres perspektiver på digital årskontrol og differentiering via kvalitative interviews.
 
# Hvordan evalueres projektet?
Projektet vil blive evalueret på, om deltagerne i det digitale forløb klarer sig lige så godt vedrørende HbA1c, som personer med type2-diabetes, der følger en standard årskontrol. 
Desuden vil projektet følge øvrige diabetesrelevante værdier, herunder blodtryk, kolesterol, eGFR og UACR, diabetes relevavant medicin og forbruget af sundhedsydelser.   

# Størrelse og lokation
Studiet gennemføres i udvalgte almen praksis beliggende i Region Midtjylland. Alle praksisser i regionen inviteres til at deltage. Målet er deltagelse fra cirka 25 almen praksis klinikker og cirka patienter medtype 2-diabetes. 
Hvis interessen for deltagelse bliver væsentligt større end studiets kapacitet vil projektet se sig nødsaget til at lukke for tilmeldinger.
Til det kvalitative interviewstudie vil cirka 15 deltagere inviteres til at deltage. 


# Identifikation og rekruttering af deltagere 
Identifikation af potentielle deltagere:  
1. Almen praksis anvender Patientlisten i Forløbsoverblikket til identifikation af patienter som opfylder de "hårde" paraklinikse inklusionskriterier (HbA1c, eGFR, UACR, LDL). Se: link til "hvem kan deltage. 
2. Ved opslag i journalen eller udfra det generelle kendskab til vurderes om patienten er egnet til digital årskontrol. Vurdering af comorbiditet, samt digitale og sproglige evner. Er der forhold som gør patienten uegnet?
Der er ikke fastsat bestemt tilstande eller komorbiditeter, som gør pateinten uegnet. Det er en invididuel afgørelse af behandleren. 
Rekrutteringsprocessen er udførligt beskrevet i bilag 2, Procedure for mundtlig deltagerinformation.
	
Rekruttering af deltagere foregår i 3 trin:
Trin 1. Besked i Min Læge-appen med forespørgsel om deltagelse (bilag 3).
Trin 2. Mundtligt deltagerinformation givet telefonisk eller ved fremmøde, hvis patienten af anden årsag er i klinikken, hvor der er tid og mulighed til afgivelse af mundtlig information (bilag 2).
Trin 3. Besked i Min Læge-appen med link til samtykke (bilag 4).


# Samtykke
Samtykke registreres direkte hos Steno Diabetes Center Aarhus og opbevares dér. 
Oplysning om deltagers samtykke videregives til almen praksis via e-Boks. 

Oplysninger fra patientjournaler

Fra patientjournalen ved egen læge:
På inklusionstidspunktet:
•	År for diabetesdebut.
•	Senest registrerede blodtryksmåling.
•	Senest registrerede vægt.
•	Senest registrerede ryge status.

Ved den efterfølgende standard årlige opfølgning (ved forsøgets afslutning):
•	Blodtryksmåling.
•	Vægt.
•	Ryge status.



# Økonomiske forhold
Forsøget er finansieret af Steno Diabetes Center Aarhus.
Deltagerne modtager ikke betaling for deltagelse i forsøget. 
Deltagende almen praksis modtager betaling for tidsforbrug til rekruttering og dataindsamling.  





